# Generated by Django 3.2.6 on 2022-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='term_cond',
            field=models.BooleanField(default=True),
        ),
    ]
