# Generated by Django 3.2.6 on 2022-10-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221019_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Collected_No',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Current_Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Running_No',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Today_Status',
            field=models.BooleanField(default=True),
        ),
    ]
