# Generated by Django 3.2.6 on 2022-09-28 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitalAdmin', '0002_auto_20220321_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ImageName',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MultyHospitalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DrDIN', models.CharField(max_length=8)),
                ('DrName', models.CharField(max_length=50)),
                ('DrType', models.CharField(choices=[('', "Doctor's Type"), ('Dentist', 'Dentist'), ('ENT', 'Ear & Nose Throught'), ('Gynaecologist', 'Gynaecologist'), ('Orthopaedic surgeon', 'Orthopaedic surgeon'), ('Paediatrician', 'Paediatrician'), ('Psychiatrists', 'Psychiatrists'), ('Physician', 'Physician'), ('Neurologist', 'Neurologist'), ('Cardiologist', 'Cardiologist'), ('Radiologist', 'Radiologist'), ('Pulmonologist', 'Pulmonologist'), ('Endocrinologist', 'Endocrinologist'), ('Oncologist', 'Oncologist'), ('Cardiothoracic', 'Cardiothoracic'), ('Veterinarian', 'Veterinarian')], max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctordetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multy_doctor_data', to='hospitalAdmin.doctordetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multy_hospital_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
