# Generated by Django 3.2.6 on 2022-10-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAdmin', '0004_auto_20220929_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitaldata',
            old_name='City',
            new_name='District',
        ),
    ]
